export interface LanguageInfo {
  code: string;
  name: string;
  nativeName: string;
  category: "indian" | "international";
  region: string;
  flag: string;
  script: string;
  direction?: "ltr" | "rtl";
  popular?: boolean;
}

export const LANGUAGES: LanguageInfo[] = [
  // --- Popular / Default ---
  {
    code: "en",
    name: "English",
    nativeName: "English",
    category: "international",
    region: "Global",
    flag: "🇬🇧",
    script: "Latin",
    direction: "ltr",
    popular: true,
  },

  // --- All 22 Scheduled Indian Languages ---
  {
    code: "hi",
    name: "Hindi",
    nativeName: "हिन्दी",
    category: "indian",
    region: "North & Central India",
    flag: "🇮🇳",
    script: "Devanagari",
    direction: "ltr",
    popular: true,
  },
  {
    code: "bn",
    name: "Bengali",
    nativeName: "বাংলা",
    category: "indian",
    region: "West Bengal & Tripura",
    flag: "🇮🇳",
    script: "Bengali",
    direction: "ltr",
    popular: true,
  },
  {
    code: "te",
    name: "Telugu",
    nativeName: "తెలుగు",
    category: "indian",
    region: "Andhra Pradesh & Telangana",
    flag: "🇮🇳",
    script: "Telugu",
    direction: "ltr",
    popular: true,
  },
  {
    code: "mr",
    name: "Marathi",
    nativeName: "मराठी",
    category: "indian",
    region: "Maharashtra & Goa",
    flag: "🇮🇳",
    script: "Devanagari",
    direction: "ltr",
    popular: true,
  },
  {
    code: "ta",
    name: "Tamil",
    nativeName: "தமிழ்",
    category: "indian",
    region: "Tamil Nadu & Puducherry",
    flag: "🇮🇳",
    script: "Tamil",
    direction: "ltr",
    popular: true,
  },
  {
    code: "gu",
    name: "Gujarati",
    nativeName: "ગુજરાતી",
    category: "indian",
    region: "Gujarat & Daman",
    flag: "🇮🇳",
    script: "Gujarati",
    direction: "ltr",
    popular: true,
  },
  {
    code: "kn",
    name: "Kannada",
    nativeName: "ಕನ್ನಡ",
    category: "indian",
    region: "Karnataka",
    flag: "🇮🇳",
    script: "Kannada",
    direction: "ltr",
    popular: true,
  },
  {
    code: "ml",
    name: "Malayalam",
    nativeName: "മലയാളം",
    category: "indian",
    region: "Kerala & Lakshadweep",
    flag: "🇮🇳",
    script: "Malayalam",
    direction: "ltr",
    popular: true,
  },
  {
    code: "or",
    name: "Odia",
    nativeName: "ଓଡ଼ିଆ",
    category: "indian",
    region: "Odisha",
    flag: "🇮🇳",
    script: "Odia",
    direction: "ltr",
    popular: true,
  },
  {
    code: "pa",
    name: "Punjabi",
    nativeName: "ਪੰਜਾਬੀ",
    category: "indian",
    region: "Punjab & Chandigarh",
    flag: "🇮🇳",
    script: "Gurmukhi",
    direction: "ltr",
    popular: true,
  },
  {
    code: "as",
    name: "Assamese",
    nativeName: "অসমীয়া",
    category: "indian",
    region: "Assam",
    flag: "🇮🇳",
    script: "Bengali-Assamese",
    direction: "ltr",
    popular: true,
  },
  {
    code: "ur",
    name: "Urdu",
    nativeName: "اردو",
    category: "indian",
    region: "Pan-India / Jammu & Kashmir",
    flag: "🇮🇳",
    script: "Perso-Arabic",
    direction: "rtl",
    popular: true,
  },
  {
    code: "sa",
    name: "Sanskrit",
    nativeName: "संस्कृतम्",
    category: "indian",
    region: "Classical / Pan-India",
    flag: "🇮🇳",
    script: "Devanagari",
    direction: "ltr",
  },
  {
    code: "mai",
    name: "Maithili",
    nativeName: "मैथिली",
    category: "indian",
    region: "Bihar & Jharkhand",
    flag: "🇮🇳",
    script: "Devanagari / Mithilakshar",
    direction: "ltr",
  },
  {
    code: "kok",
    name: "Konkani",
    nativeName: "कोंकणी",
    category: "indian",
    region: "Goa & Coastal Karnataka",
    flag: "🇮🇳",
    script: "Devanagari",
    direction: "ltr",
  },
  {
    code: "ne",
    name: "Nepali",
    nativeName: "नेपाली",
    category: "indian",
    region: "Sikkim & West Bengal",
    flag: "🇮🇳",
    script: "Devanagari",
    direction: "ltr",
  },
  {
    code: "sd",
    name: "Sindhi",
    nativeName: "سنڌي / सिन्धी",
    category: "indian",
    region: "Gujarat & Maharashtra",
    flag: "🇮🇳",
    script: "Arabic / Devanagari",
    direction: "rtl",
  },
  {
    code: "doi",
    name: "Dogri",
    nativeName: "डोगरी",
    category: "indian",
    region: "Jammu & Kashmir & Himachal",
    flag: "🇮🇳",
    script: "Devanagari",
    direction: "ltr",
  },
  {
    code: "ks",
    name: "Kashmiri",
    nativeName: "کٲشُر / कॉशुर",
    category: "indian",
    region: "Jammu & Kashmir",
    flag: "🇮🇳",
    script: "Perso-Arabic / Devanagari",
    direction: "rtl",
  },
  {
    code: "mni",
    name: "Manipuri (Meitei)",
    nativeName: "মৈতৈলোন্ / ꯃꯤꯇꯩꯂꯣꯟ",
    category: "indian",
    region: "Manipur",
    flag: "🇮🇳",
    script: "Bengali / Meetei Mayek",
    direction: "ltr",
  },
  {
    code: "sat",
    name: "Santali",
    nativeName: "ᱥᱟᱱᱛᱟᱲᱤ",
    category: "indian",
    region: "Jharkhand, Odisha & Bengal",
    flag: "🇮🇳",
    script: "Ol Chiki",
    direction: "ltr",
  },
  {
    code: "brx",
    name: "Bodo",
    nativeName: "बर'",
    category: "indian",
    region: "Assam & Bodoland",
    flag: "🇮🇳",
    script: "Devanagari",
    direction: "ltr",
  },

  // --- Popular International Languages ---
  {
    code: "es",
    name: "Spanish",
    nativeName: "Español",
    category: "international",
    region: "Spain & Latin America",
    flag: "🇪🇸",
    script: "Latin",
    direction: "ltr",
    popular: true,
  },
  {
    code: "fr",
    name: "French",
    nativeName: "Français",
    category: "international",
    region: "France & Francophonie",
    flag: "🇫🇷",
    script: "Latin",
    direction: "ltr",
    popular: true,
  },
  {
    code: "de",
    name: "German",
    nativeName: "Deutsch",
    category: "international",
    region: "Germany, Austria & Swiss",
    flag: "🇩🇪",
    script: "Latin",
    direction: "ltr",
    popular: true,
  },
  {
    code: "ja",
    name: "Japanese",
    nativeName: "日本語",
    category: "international",
    region: "Japan",
    flag: "🇯🇵",
    script: "Kanji & Kana",
    direction: "ltr",
    popular: true,
  },
  {
    code: "zh-CN",
    name: "Chinese (Simplified)",
    nativeName: "简体中文",
    category: "international",
    region: "China & Singapore",
    flag: "🇨🇳",
    script: "Simplified Han",
    direction: "ltr",
    popular: true,
  },
  {
    code: "zh-TW",
    name: "Chinese (Traditional)",
    nativeName: "繁體中文",
    category: "international",
    region: "Taiwan & Hong Kong",
    flag: "🇹🇼",
    script: "Traditional Han",
    direction: "ltr",
  },
  {
    code: "ru",
    name: "Russian",
    nativeName: "Русский",
    category: "international",
    region: "Russia & Eastern Europe",
    flag: "🇷🇺",
    script: "Cyrillic",
    direction: "ltr",
    popular: true,
  },
  {
    code: "pt",
    name: "Portuguese",
    nativeName: "Português",
    category: "international",
    region: "Portugal & Brazil",
    flag: "🇵🇹",
    script: "Latin",
    direction: "ltr",
    popular: true,
  },
  {
    code: "it",
    name: "Italian",
    nativeName: "Italiano",
    category: "international",
    region: "Italy & Switzerland",
    flag: "🇮🇹",
    script: "Latin",
    direction: "ltr",
    popular: true,
  },
  {
    code: "ko",
    name: "Korean",
    nativeName: "한국어",
    category: "international",
    region: "South Korea",
    flag: "🇰🇷",
    script: "Hangul",
    direction: "ltr",
    popular: true,
  },
  {
    code: "ar",
    name: "Arabic",
    nativeName: "العربية",
    category: "international",
    region: "Middle East & North Africa",
    flag: "🇦🇪",
    script: "Arabic",
    direction: "rtl",
    popular: true,
  },
  {
    code: "th",
    name: "Thai",
    nativeName: "ไทย",
    category: "international",
    region: "Thailand",
    flag: "🇹🇭",
    script: "Thai",
    direction: "ltr",
    popular: true,
  },
  {
    code: "vi",
    name: "Vietnamese",
    nativeName: "Tiếng Việt",
    category: "international",
    region: "Vietnam",
    flag: "🇻🇳",
    script: "Latin",
    direction: "ltr",
  },
  {
    code: "id",
    name: "Indonesian",
    nativeName: "Bahasa Indonesia",
    category: "international",
    region: "Indonesia",
    flag: "🇮🇩",
    script: "Latin",
    direction: "ltr",
  },
  {
    code: "tr",
    name: "Turkish",
    nativeName: "Türkçe",
    category: "international",
    region: "Turkey",
    flag: "🇹🇷",
    script: "Latin",
    direction: "ltr",
  },
  {
    code: "nl",
    name: "Dutch",
    nativeName: "Nederlands",
    category: "international",
    region: "Netherlands & Belgium",
    flag: "🇳🇱",
    script: "Latin",
    direction: "ltr",
  },
  {
    code: "fa",
    name: "Persian (Farsi)",
    nativeName: "فارسی",
    category: "international",
    region: "Iran & Central Asia",
    flag: "🇮🇷",
    script: "Perso-Arabic",
    direction: "rtl",
  },
  {
    code: "pl",
    name: "Polish",
    nativeName: "Polski",
    category: "international",
    region: "Poland",
    flag: "🇵🇱",
    script: "Latin",
    direction: "ltr",
  },
  {
    code: "sv",
    name: "Swedish",
    nativeName: "Svenska",
    category: "international",
    region: "Sweden & Finland",
    flag: "🇸🇪",
    script: "Latin",
    direction: "ltr",
  },
  {
    code: "he",
    name: "Hebrew",
    nativeName: "עברית",
    category: "international",
    region: "Israel",
    flag: "🇮🇱",
    script: "Hebrew",
    direction: "rtl",
  },
  {
    code: "el",
    name: "Greek",
    nativeName: "Ελληνικά",
    category: "international",
    region: "Greece & Cyprus",
    flag: "🇬🇷",
    script: "Greek",
    direction: "ltr",
  },
];

export const INDIAN_LANGUAGES = LANGUAGES.filter((l) => l.category === "indian");
export const INTERNATIONAL_LANGUAGES = LANGUAGES.filter((l) => l.category === "international");
export const POPULAR_LANGUAGES = LANGUAGES.filter((l) => l.popular);

export function getLanguageByCode(code: string): LanguageInfo {
  const found = LANGUAGES.find(
    (l) => l.code.toLowerCase() === code.toLowerCase() || 
           (code === "zh" && l.code === "zh-CN") ||
           (code === "od" && l.code === "or")
  );
  return (
    found || {
      code,
      name: code.toUpperCase(),
      nativeName: code.toUpperCase(),
      category: "international",
      region: "Global",
      flag: "🌐",
      script: "Latin",
      direction: "ltr",
    }
  );
}

export function searchLanguages(query: string): LanguageInfo[] {
  const q = query.trim().toLowerCase();
  if (!q) return LANGUAGES;
  return LANGUAGES.filter(
    (l) =>
      l.name.toLowerCase().includes(q) ||
      l.nativeName.toLowerCase().includes(q) ||
      l.code.toLowerCase().includes(q) ||
      l.region.toLowerCase().includes(q) ||
      l.script.toLowerCase().includes(q)
  );
}

