"use client";

import { useMemo, useState } from "react";
import { Check, Download, Mail } from "lucide-react";
import { REGIONS, THEMES } from "@/data/content";
import {
  generateItinerary,
  type ItineraryInput,
} from "@/lib/itinerary";
import type { Region } from "@/lib/types";
import { useLanguage } from "@/lib/i18n";
import { cn, isValidEmail } from "@/lib/utils";

const lengths = [
  { value: "4" as const, label: "4 days" },
  { value: "7" as const, label: "7 days" },
  { value: "10" as const, label: "10 days" },
  { value: "14" as const, label: "2 weeks" },
];

const budgets = ["Budget", "Mid-range", "Luxury"] as const;

export function ItineraryBuilder() {
  const { t } = useLanguage();
  const [step, setStep] = useState(0);
  const [tripLength, setTripLength] =
    useState<ItineraryInput["tripLength"]>("7");
  const [interests, setInterests] = useState<string[]>([]);
  const [budget, setBudget] =
    useState<ItineraryInput["budget"]>("Mid-range");
  const [region, setRegion] = useState<Region | "Flexible">("Flexible");
  const [result, setResult] = useState<ReturnType<typeof generateItinerary> | null>(
    null,
  );
  const [downloadState, setDownloadState] = useState<"idle" | "done">("idle");
  const [emailState, setEmailState] = useState<"idle" | "loading" | "done" | "error">(
    "idle",
  );
  const [email, setEmail] = useState("");
  const [emailError, setEmailError] = useState("");

  const steps = ["Trip length", "Interests", "Budget & style", "Region", "Your arc"];

  function toggleInterest(theme: string) {
    setInterests((prev) =>
      prev.includes(theme) ? prev.filter((t) => t !== theme) : [...prev, theme],
    );
  }

  function build() {
    const generated = generateItinerary({
      tripLength,
      interests,
      budget,
      region,
    });
    setResult(generated);
    setStep(4);
    setDownloadState("idle");
    setEmailState("idle");
  }

  function download() {
    if (!result) return;
    const lines = [
      result.title,
      result.summary,
      "",
      ...result.days.flatMap((d) => [
        `Day ${d.day} — ${d.title}`,
        ...d.activities.map((a) => `  • ${a}`),
        `  Stay: ${d.stay}`,
        `  Meals: ${d.meals}`,
        "",
      ]),
      "Generated by Explore India — independent travel platform",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `explore-india-itinerary-${tripLength}d.txt`;
    a.click();
    URL.revokeObjectURL(url);
    setDownloadState("done");
  }

  async function emailItinerary(e: React.FormEvent) {
    e.preventDefault();
    if (!result) return;
    setEmailError("");
    if (!isValidEmail(email)) {
      setEmailError(t.common.invalidEmail);
      return;
    }
    setEmailState("loading");
    try {
      const res = await fetch("/api/itinerary", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          email,
          tripLength,
          interests,
          budget,
          region,
          title: result.title,
          days: result.days,
        }),
      });
      if (!res.ok) throw new Error("Could not save itinerary.");
      setEmailState("done");
    } catch {
      setEmailState("error");
      setEmailError("Could not email itinerary. Please try again.");
    }
  }

  const canNext = useMemo(() => {
    if (step === 1) return interests.length > 0;
    return true;
  }, [step, interests]);

  return (
    <div className="card-surface overflow-hidden">
      <div className="border-b border-dusk-ink/10 bg-surface-elevated px-5 py-4 sm:px-8">
        <ol className="flex flex-wrap gap-2" aria-label="Itinerary steps">
          {steps.map((label, i) => (
            <li key={label}>
              <button
                type="button"
                onClick={() => {
                  if (i < 4) setStep(i);
                  else if (result) setStep(4);
                }}
                className={cn(
                  "rounded-full px-3 py-1.5 text-xs font-semibold uppercase tracking-wider",
                  i === step
                    ? "bg-peacock text-warm-white"
                    : i < step
                      ? "bg-peacock/15 text-peacock"
                      : "bg-warm-white text-ink-muted",
                )}
                aria-current={i === step ? "step" : undefined}
              >
                {i + 1}. {label}
              </button>
            </li>
          ))}
        </ol>
      </div>

      <div className="p-5 sm:p-8">
        {step === 0 ? (
          <fieldset>
            <legend className="font-display text-2xl text-dusk-ink">
              How many days do you have?
            </legend>
            <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
              {lengths.map((l) => (
                <button
                  key={l.value}
                  type="button"
                  onClick={() => setTripLength(l.value)}
                  className={cn(
                    "rounded-2xl border px-4 py-6 text-left transition",
                    tripLength === l.value
                      ? "border-peacock bg-peacock/10"
                      : "border-dusk-ink/10 hover:border-peacock/40",
                  )}
                  aria-pressed={tripLength === l.value}
                >
                  <span className="font-display text-2xl">{l.label}</span>
                </button>
              ))}
            </div>
          </fieldset>
        ) : null}

        {step === 1 ? (
          <fieldset>
            <legend className="font-display text-2xl text-dusk-ink">
              What are you hungry for?
            </legend>
            <p className="mt-2 text-sm text-ink-muted">Select one or more themes.</p>
            <div className="mt-6 flex flex-wrap gap-2">
              {THEMES.map((theme) => {
                const active = interests.includes(theme);
                return (
                  <button
                    key={theme}
                    type="button"
                    onClick={() => toggleInterest(theme)}
                    className={cn("chip", active && "chip-active")}
                    aria-pressed={active}
                  >
                    {active ? <Check className="h-3.5 w-3.5" aria-hidden /> : null}
                    {theme}
                  </button>
                );
              })}
            </div>
          </fieldset>
        ) : null}

        {step === 2 ? (
          <fieldset>
            <legend className="font-display text-2xl text-dusk-ink">
              Budget & lodging style
            </legend>
            <div className="mt-6 grid gap-3 sm:grid-cols-3">
              {budgets.map((b) => (
                <button
                  key={b}
                  type="button"
                  onClick={() => setBudget(b)}
                  className={cn(
                    "rounded-2xl border px-4 py-6 text-left transition",
                    budget === b
                      ? "border-peacock bg-peacock/10"
                      : "border-dusk-ink/10 hover:border-peacock/40",
                  )}
                  aria-pressed={budget === b}
                >
                  <span className="font-display text-xl">{b}</span>
                  <span className="mt-2 block text-sm text-ink-muted">
                    {b === "Budget"
                      ? "Guesthouses, trains, street kitchens"
                      : b === "Mid-range"
                        ? "Boutique stays, mixed transport"
                        : "Private guides, heritage hotels"}
                  </span>
                </button>
              ))}
            </div>
          </fieldset>
        ) : null}

        {step === 3 ? (
          <fieldset>
            <legend className="font-display text-2xl text-dusk-ink">
              Region preference
            </legend>
            <div className="mt-6 flex flex-wrap gap-2">
              <button
                type="button"
                onClick={() => setRegion("Flexible")}
                className={cn("chip", region === "Flexible" && "chip-active")}
                aria-pressed={region === "Flexible"}
              >
                Flexible
              </button>
              {REGIONS.map((r) => (
                <button
                  key={r}
                  type="button"
                  onClick={() => setRegion(r)}
                  className={cn("chip", region === r && "chip-active")}
                  aria-pressed={region === r}
                >
                  {r}
                </button>
              ))}
            </div>
          </fieldset>
        ) : null}

        {step === 4 && result ? (
          <div>
            <h3 className="font-display text-3xl text-dusk-ink">{result.title}</h3>
            <p className="mt-3 max-w-3xl text-ink-muted">{result.summary}</p>
            <ol className="relative mt-10 space-y-0 border-l-2 border-turmeric/60 pl-6">
              {result.days.map((day) => (
                <li key={day.day} className="relative pb-10">
                  <span className="absolute -left-[31px] top-1 flex h-6 w-6 items-center justify-center rounded-full bg-turmeric text-xs font-bold text-dusk-ink">
                    {day.day}
                  </span>
                  <h4 className="font-display text-xl text-dusk-ink">{day.title}</h4>
                  <ul className="mt-3 space-y-1.5 text-sm text-ink-muted">
                    {day.activities.map((a) => (
                      <li key={a}>• {a}</li>
                    ))}
                  </ul>
                  <p className="mt-3 text-sm">
                    <span className="font-semibold text-saffron">Stay:</span>{" "}
                    {day.stay}
                  </p>
                  <p className="text-sm">
                    <span className="font-semibold text-saffron">Meals:</span>{" "}
                    {day.meals}
                  </p>
                </li>
              ))}
            </ol>

            <div className="mt-4 flex flex-wrap gap-3">
              <button type="button" className="btn-primary" onClick={download}>
                <Download className="h-4 w-4" aria-hidden />
                {downloadState === "done" ? "Downloaded" : t.common.download}
              </button>
            </div>

            <form
              onSubmit={emailItinerary}
              className="mt-6 rounded-2xl border border-dusk-ink/10 bg-surface-elevated p-5"
            >
              <p className="text-sm font-semibold text-dusk-ink">
                {t.common.emailItinerary}
              </p>
              <div className="mt-3 flex flex-col gap-2 sm:flex-row">
                <label className="sr-only" htmlFor="itinerary-email">
                  Email
                </label>
                <input
                  id="itinerary-email"
                  type="email"
                  value={email}
                  onChange={(e) => {
                    setEmail(e.target.value);
                    setEmailError("");
                  }}
                  placeholder="you@email.com"
                  className="w-full rounded-full border border-navy/15 bg-white px-4 py-3 text-sm outline-none focus:border-saffron"
                />
                <button
                  type="submit"
                  className="btn-ghost shrink-0"
                  disabled={emailState === "loading" || emailState === "done"}
                >
                  <Mail className="h-4 w-4" aria-hidden />
                  {emailState === "loading"
                    ? t.common.sending
                    : emailState === "done"
                      ? t.common.sent
                      : "Email me this"}
                </button>
              </div>
              {emailError ? (
                <p className="mt-2 text-sm text-rani" role="alert">
                  {emailError}
                </p>
              ) : null}
              {emailState === "done" ? (
                <p className="mt-2 text-sm text-saffron" role="status">
                  Itinerary saved and marked for email delivery.
                </p>
              ) : null}
            </form>
          </div>
        ) : null}

        {step < 4 ? (
          <div className="mt-10 flex flex-wrap justify-between gap-3">
            <button
              type="button"
              className="btn-ghost"
              onClick={() => setStep((s) => Math.max(0, s - 1))}
              disabled={step === 0}
            >
              Back
            </button>
            {step < 3 ? (
              <button
                type="button"
                className="btn-primary"
                disabled={!canNext}
                onClick={() => setStep((s) => s + 1)}
              >
                Continue
              </button>
            ) : (
              <button type="button" className="btn-primary" onClick={build}>
                Build my itinerary
              </button>
            )}
          </div>
        ) : (
          <div className="mt-8">
            <button
              type="button"
              className="btn-ghost"
              onClick={() => {
                setStep(0);
                setResult(null);
              }}
            >
              Start over
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
